version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: moonshot-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    command:
      "postgres -c 'max_connections=500'"
    restart: always
  web:
    build: .
    command: './bin/rails server'
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres_data:
  app-storage:
